import { Container } from 'react-bootstrap';
import Head from 'next/head'
import Layout from './Layout';


export default function PrivacyPolicy() {



	return (
		<>
		<Layout>
			<Head>
				<title>Privacy Policy</title>
			</Head>
			<div className='Bann'>
				<div className='baner_wrapper'><img src='/indexImg/Privacy-Policy.webp' /></div>
			</div>
			<div className='contentSections'>
				<Container>

					<div className='heading'>INTERPRETATION AND DEFINITIONS</div>

					<div className='mainDiv'>
						<div className='runningHeadng'>Interpretation</div>
						<p className='runTextP'>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
					</div>

					<div className='mainDiv'>
						<div className='runningHeadng'>Definitions</div>
						<div className='runTextP'>For the purposes of this Privacy Policy:</div>
						<ul className='ulText mt-3'>
							<li><strong>Account</strong> means a unique account created for you to access our Service or parts of our Service.</li>
							<li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
								<li><strong>Company</strong>  (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Forever Books Private Limited, 4583/15, Daryaganj, New Delhi - 110002 India.</li>
								<li><strong>Cookies</strong>  are small files that are placed on your computer, mobile device or any other device by a website, containing the details of your browsing history on that website among its many uses.</li>
								<li><strong>Country</strong>  refers to: Delhi, India</li>
								<li><strong>Device</strong>  means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
								<li><strong>Personal Data</strong>  is any information that relates to an identified or identifiable individual.</li>
								<li><strong>Service</strong> refers to the Website. </li>
								<li><strong> Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
								<li><strong>Usage Data</strong>  refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
								<li><strong>Website refers</strong> to Forever Books, accessible from https://books.foreverbooks.co.in </li>
								<li><strong>You</strong>  means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
						
						</ul>
						<div className='heading mt-3'>COLLECTING AND USING YOUR PERSONAL DATA<br />
							Types of Data Collected</div>
					</div>


					<div className='mainDiv'>
						<div className='runningHeadng'>Personal Data</div>
						<div className='runTextP'>While using Our Service, We may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to:</div>
						<ul className='ulText mt-3'>
							<li>Email address</li>
							<li>First name and last name</li>
							<li>Phone number</li>
							<li>Address, State, Province, ZIP/Postal code, City</li>
							<li>Usage Data</li>
						</ul>
					</div>

					<div className='mainDiv'>
						<div className='runningHeadng'>Usage Data</div>
						<div className='runTextP'>Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data. When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.<br />
							We may also collect information that your browser sends whenever you visit our Service or when you access the Service by or through a mobile device.</div>

					</div>
					<div className='mainDiv'>
						<div className='runningHeadng'>Tracking Technologies and Cookies</div>
						<div className='runTextP'>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies we use may include:</div>
						<ul className='ulText mt-3'>
							<li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if you do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
							<li><strong>Web Beacons.</strong>Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>

						</ul>
						<div className='runTextP'>Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on your personal computer or mobile device when you go offline, while Session Cookies are deleted as soon as you close Your web browser.</div>
						<div className='runTextP mt-3'>We use both Session and Persistent Cookies for the purposes set out below:</div>
						<ul className='ulText mt-3'>
							<li><strong>Necessary / Essential Cookies</strong> <br />
								Type: Session Cookies  <br />
								Administered by: Us  <br />
								Purpose: These Cookies are essential to provide you with services available through the Website and to enable you to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that you have asked for cannot be provided, and we only use these Cookies to provide You with those services.
							</li>
							<li><strong>Cookies Policy / Notice Acceptance Cookies</strong> <br />
								Type: Persistent Cookies <br />
								Administered by: Us  <br />
								Purpose: These Cookies identify if users have accepted the use of cookies on the Website.
							</li>
							<li><strong>Functionality Cookies</strong> <br />
								Type: Persistent Cookies Administered by: Us Purpose: These Cookies allow us to remember choices you make when you use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide you with a more personal experience and to avoid you having to re-enter your preferences every time you use the Website.
							</li>
						</ul>
						<div className='runTextP'>For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</div>
					</div>

					<div className='mainDiv'>
						<div className='runningHeadng'>Use of Your Personal Data</div>
						<div className='runTextP'>The Company may use Personal Data for the following purposes:</div>
						<ul className='ulText mt-3'>
							<li><strong>To provide and maintain our Service,</strong> including to monitor the usage of our Service.</li>
							<li><strong> To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data you provide can give you access to different functionalities of the Service that are available to you as a registered user.</li>
							<li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services you have purchased or of any other contract with us through the Service. </li>
							<li><strong>To contact You:</strong> by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
							<li><strong>To provide You with news,</strong>  special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</li>
							<li><strong>To manage Your requests:</strong>  To attend and manage Your requests to Us.</li>
							<li><strong>For business transfers:</strong> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred. </li>
							<li><strong> For other purposes:</strong> We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</li>
						</ul>
						<div className='runningHeadng'>We may share your personal information in the following situations:</div>
						<ul className='ulText mt-3'>
							<li><strong>With Service Providers:</strong>  We may share your personal information with Service Providers to monitor and analyze the use of our Service, to contact you.</li>
							<li><strong>For business transfers:</strong>  We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
							<li><strong> With Affiliates: </strong>We may share your information with our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include our parent company and any other subsidiaries, joint venture partners or other companies that we control or that are under common control with us.</li>
							<li><strong>With business partners:</strong>  We may share your information with our business partners to offer you certain products, services or promotions.</li>
							<li><strong>With other users:</strong> when you share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside. </li>
							<li><strong> With Your consent:</strong> We may disclose your personal information for any other purpose with your consent.</li>

						</ul>
					</div>
					<div className='mainDiv'>
						<div className='runningHeadng'>Retention of Your Personal Data</div>
						<div className='runTextP'>The Company will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
							The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or we are legally obligated to retain this data for longer time periods.</div>

					</div>
					<div className='mainDiv'>
						<div className='runningHeadng'>Transfer of Your Personal Data</div>
						<div className='runTextP'>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.<br />
							Your consent to this Privacy Policy followed by your submission of such information represents Your agreement to that transfer.
							The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.</div>
					</div>
					<div className='mainDiv'>
						<div className='runningHeadng'>Delete Your Personal Data</div>
						<div className='runTextP'>You have the right to delete or request that we assist in deleting the Personal Data that we have collected about you.<br />
							Our Service may give you the ability to delete certain information about you from within the Service. You may update, amend, or delete your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage your personal information. You may also contact us to request access to, correct, or delete any personal information that you have provided to us. <br />
							Please note, however, that we may need to retain certain information when we have a legal obligation or lawful basis to do so.</div>

						<div className='runTextP mt-5'>Disclosure of Your Personal Data</div>
					</div>
					<div className='mainDiv'>
						<div className='runningHeadng'>Business Transactions</div>
						<div className='runTextP'>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.<br />
						</div>
					</div>
					<div className='mainDiv'>
						<div className='runningHeadng'>Law enforcement</div>
						<div className='runTextP'>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).<br />
						</div>
					</div>

					<div className='mainDiv'>
						<div className='runningHeadng'>Other legal requirements</div>
						<div className='runTextP'>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
						</div>
						<ul className='ulText mt-3'>
							<li>Comply with a legal obligation</li>
							<li>Protect and defend the rights or property of the Company</li>
							<li>Prevent or investigate possible wrongdoing in connection with the Service</li>
							<li>Protect the personal safety of Users of the Service or the public</li>
							<li>Protect against legal liability</li>
						</ul>

					</div>
					<div className='mainDiv'>
						<div className='runningHeadng'>Security of Your Personal Data</div>
						<div className='runTextP'>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If you are a parent or guardian and you are aware that your child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from anyone under the age of 13 without verification of parental consent, we take steps to remove that information from our servers.<br />
							If we need to rely on consent as a legal basis for processing your information and your country requires consent from a parent, we may require your parent's consent before we collect and use that information.
						</div>
					</div>
					<div className='mainDiv'>
						<div className='runningHeadng'>Links to Other Websites</div>
						<div className='runTextP'>Our Service may contain links to other websites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.<br />
							We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
						</div>
					</div>
					<div className='mainDiv'>
						<div className='runningHeadng'>Changes to this Privacy Policy</div>
						<div className='runTextP'>We may update Our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.<br/>
							We will let you know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.<br/>
							You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
						</div>
					</div>
					<div className='mainDiv'>
						<div className='runningHeadng'>Contact Us</div>
						<div className='runTextP'>If you have any questions about this Privacy Policy, You can contact us:</div>
						<ul className='ulText mt-3'>
							<li>By email: info@foreverbooks.co.in</li>
							<li>By phone number: 9717998857</li>
						</ul>

					</div>

				</Container>
			</div>
			</Layout>
		</>
	)
}
